### ISSUE TITLE
Not Detecting SIM card

### ISSUE THREAD

**Issue by Johnkarazou** [sonyxperiadev/device-sony-pdx203#8]
Hello, 
It appears that both A13 and A14 are having issues with SIM detection. (XQ-AT51) (grey SIM, no signal, no SIM)
Not sure if I should/can provide any logs or any more information abou this, but If needed, let me know what you need. 

Other than that, I haven't noticed anything else (of course I can't test it 100%)

Thank you.

**Comment by jerpelea** [comment]
Thanks for reporting the bug
I will investigate it ASAP on this device

Best regards
Alin

**Comment by jerpelea** [comment]
please use the bugtracker 
https://github.com/sonyxperiadev/bug_tracker/

**Comment by jerpelea** [comment]
please follow the steps: 
1. use flashtool and flash 58.0.A.3.194 
2. sync the latest AOSP Android 13 code and build the AOSP images
3. flash the device with latest vendor image and the AOSP built at step 3
